version: "3.1"

services:
  app:
    image: node:10
    working_dir: /app
    ports:
      - 3005:3005
    volumes:
      - .:/app
    command: npm start

  mysql:
    image: mysql:8.0.19
    environment:
      MYSQL_USER: "nogohr"
      MYSQL_PASSWORD: "passw0rd"
      MYSQL_DATABASE: "nogohr"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - 3306:3306
    volumes:
      - data-mysql:/var/lib/mysql

  mailtrap:
      image: eaudeweb/mailtrap
      environment:
        MT_USER: 'mailtrap'
        MT_PASSWD: 'mailtrap'
      ports:
        - 8025:80

volumes:
  data-mysql:
    driver: local
